apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-neo4j-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-neo4j-connector
  template:
    metadata:
      labels:
        app: kafka-neo4j-connector
    spec:
      containers:
        - name: kafka-neo4j-connector
          image: veedata/kafka-neo4j-connect
          ports:
            - containerPort: 8083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: kafka-service:29092
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_GROUP_ID
              value: kafka-neo4j-group
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: connect-configs
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: connect-offsets
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: connect-statuses
            - name: CONNECT_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: "localhost"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-neo4j-connector-service
spec:
  type: NodePort
  selector:
    app: kafka-neo4j-connector
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083
